name: Java CI with Gradle

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Run SonarQube Scan
      run: |
          echo "SONAR URL - > " ${{vars.SONAR_HOST_URL}}
          export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
          export SONAR_HOST_URL=${{vars.SONAR_HOST_URL}}
          gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
            -D sonar.projectKey=test-maven-project \
            -D sonar.host.url=$SONAR_HOST_URL \
            -D sonar.login=admin -D sonar.password=admin123 

    - name: Publish package
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publish
      env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
